name: Notify Telegram on Commit or PR

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_EVENT: ${{ github.event_name }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}

        run: |
          MESSAGE="🚀 *GitHub Update:*\n"
          if [ "$GITHUB_EVENT" = "push" ]; then
            MESSAGE+="*New Commit in ${GITHUB_REPO}*\n"
            MESSAGE+="👤 Author: ${GITHUB_ACTOR}\n"
            MESSAGE+="📝 Message: ${GITHUB_COMMIT_MESSAGE}\n"
            MESSAGE+="🔗 [View Repository](https://github.com/${GITHUB_REPO})"
          elif [ "$GITHUB_EVENT" = "pull_request" ]; then
            MESSAGE+="*Pull Request in ${GITHUB_REPO}*\n"
            MESSAGE+="👤 Author: ${GITHUB_ACTOR}\n"
            MESSAGE+="📌 Title: ${GITHUB_PR_TITLE}\n"
            MESSAGE+="🔗 [View PR](${GITHUB_PR_URL})"
          fi

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "text=${MESSAGE}" \
            -d "parse_mode=Markdown"
