name: Kotlin Lint

on:
  push:
    branches: [ main, workspace ]
    paths:
      - '**/*.kt'
      - '**/*.kts'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run ktlint
      uses: ScaCap/action-ktlint@v1.7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: true
        ktlint_version: 0.50.0
