name: Kotlin Tests

on:
  push:
    branches: [ main, workspace ]
    paths:
      - 'backend/KotlinTranslation/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/KotlinTranslation/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x backend/KotlinTranslation/gradlew

    - name: Run tests
      run: |
        cd backend/KotlinTranslation
        ./gradlew test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: backend/KotlinTranslation/build/reports/tests/
