name: StarApp Tests

on:
  push:
    branches: [ main, workspace ]
    paths:
      - 'StarApp/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'StarApp/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for root gradlew
        run: chmod +x ./gradlew

      - name: Run StarApp unit tests
        run: ./gradlew :StarApp:app:testDebugUnitTest --no-daemon

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: starapp-test-report
          path: StarApp/app/build/reports/tests/testDebugUnitTest
